# Generated by Django 4.2.7 on 2023-12-02 06:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('number', models.CharField(help_text='Вводите только числа', max_length=8, primary_key=True, serialize=False, verbose_name='id допуска')),
                ('title', models.CharField(max_length=35, verbose_name='Наименование допуска')),
                ('body', models.TextField(verbose_name='Полное наименование допуска')),
                ('knowledge', models.CharField(max_length=128, verbose_name='Область знаний')),
                ('type', models.CharField(max_length=128, verbose_name='Наименование вида допуска')),
            ],
            options={
                'verbose_name': 'Допуск',
                'verbose_name_plural': 'Допуска',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=256)),
                ('title', models.CharField(max_length=256, verbose_name='Наименование предприятия')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('slug', models.SlugField(auto_created=True, max_length=256)),
                ('number', models.CharField(help_text='Вводите только число', max_length=8, primary_key=True, serialize=False, verbose_name='ТабельныйНомер')),
                ('surname', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('appointed', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата назначения на должность')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_administrator', models.BooleanField(default=False)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elprotection.employ', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CL', 'Сдал'), ('WR', 'Скоро истечет'), ('EX', 'Нет допуска')], default='EX', max_length=2, verbose_name='Статус')),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата протокола')),
                ('number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер протокола')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания допуска')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elprotection.admission', verbose_name='Допуск')),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elprotection.employ', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протокола',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название штатной должности')),
                ('category', models.CharField(choices=[('WO', 'Рабочий'), ('MG', 'Руководитель'), ('SP', 'Специалист')], default='WO', max_length=2, verbose_name='Категория должности')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elprotection.company')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='employ',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employs', to='elprotection.position'),
        ),
        migrations.AddField(
            model_name='employ',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
