# Generated by Django 4.2.7 on 2023-11-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elprotection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name': 'Допуск', 'verbose_name_plural': 'Допуска'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='employ',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-created'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'verbose_name': 'Протокол', 'verbose_name_plural': 'Протокола'},
        ),
    ]
