# Generated by Django 4.2.7 on 2023-11-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elprotection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='administrator',
        ),
        migrations.AddField(
            model_name='employ',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
